defaults:
  - model: weight_container
  - optimizer: casadi
  - predictor: euler_multistep

_target_: rcognita.actors.ActorMPC

###---Constructor arguments---###

prediction_horizon: 8
dim_output: $ simulator.system.dim_input
dim_input: $ simulator.system.dim_output
discount_factor: 1.
action_bounds: $ controller.action_bounds
action_init: $ action_init
critic: $ controller.actor.safe_controller.critic
running_objective: $ running_objective


predictor:
  pred_step_size_multiplier%%: 12
  n_steps: 6
  prediction_horizon: 8