defaults:
  - actor: calf
  - critic: calf
  - override actor/optimizer: casadi
  - override critic/optimizer: casadi

_target_: rcognita.controllers.CALFControllerExPost

###---Constructor arguments---###

time_start: $ simulator.time_start
sampling_time: 1.0E-2
is_fixed_critic_weights: false

F_min%%: -30.
F_max%%: 30.

critic_period: = ${.critic_period_multiplier%%} * ${.sampling_time}
action_bounds: = numpy.array([[${.F_min%%}, ${.F_max%%}]])

critic_period_multiplier%%: 1

###---Overrides---###

critic:
  is_predictive: false

actor:
  predictor:
    prediction_horizon: 1




