_target_: rcognita.controllers.ControllerCartPolePID

###---Constructor arguments---###

action_bounds: = numpy.array([[${.F_min%%}, ${.F_max%%}]])
time_start: $ simulator.time_start
state_init: $ state_init
sampling_time: 1.0E-2
PID_swing_up_parameters: = [-15, 0, -10]
PID_cart_parameters: = [30, 3, 7]


F_min%%: -300.
F_max%%: 300.
