_target_: rcognita.controllers.NominalControllerInvertedPendulum

###---Constructor arguments---###

time_start: $ simulator.time_start
sampling_time: 1.0E-2
action_bounds: $ system.action_bounds%%
controller_gain: 20
