_target_: rcognita.models.GaussianPDFModel

dim_input: $ controller.actor.dim_observation
dim_action: $ controller.actor.dim_action
use_derivative: $ controller.actor.is_use_derivative
diag_scale_coef: $ system_specific.diag_scale_coef 
weight_max: 1
weight_min: = None

