_target_: rcognita.predictors.EulerPredictor

pred_step_size: =  ${controller.actor.predictor.pred_step_size}
system: $ simulator.system
dim_output: $ controller.actor.dim_output
prediction_horizon: $ actor.predictior.prediction_horizon
