defaults:
  - model: quad_no_mix
  - optimizer: scipy

dim_input: $ system.dim_input
dim_output: $ dim_output
data_buffer_size: $ data_buffer_size
optimizer: $ optimizer
running_objective: $ running_objective
discount_factor: $ discount_factor
sampling_time: $ sampling_time
critic_regularization_param: $ critic_regularization_param
