_target_: rcognita.predictors.EulerPredictor

pred_step_size: = ${controller.sampling_time} * ${.pred_step_size_multiplier%%}
system: $ simulator.system
dim_input: $ controller.actor.dim_input
prediction_horizon: 5

pred_step_size_multiplier%%: 2
