_target_: rcognita.predictors.RKPredictor

###---Constructor arguments---###

pred_step_size: = ${controller.sampling_time} * ${.pred_step_size_multiplier%%}
system: $ system
dim_output: $ controller.actor.dim_output
prediction_horizon: $ prediction_horizon
state_or_observation_init: $ state_init
action_init: $ action_init

pred_step_size_multiplier%%: 2
