defaults:
  - model: weight_container
  - optimizer: scipy
  - predictor: euler

prediction_horizon: 4
dim_input: $ simulator.system.dim_input
dim_output: $ simulator.system.dim_output
discount_factor: 1
action_bounds: = numpy.array([[${controller.F_min%%}, ${controller.F_max%%}], [${controller.M_min%%}, ${controller.M_max%%}]])
action_init: $ action_init
critic: $ controller.critic
