defaults:
  - model: weight_container
  - optimizer: scipy

prediction_horizon: 4
dim_input: $ system.dim_input
dim_output: $ system.dim_output
discount_factor: $ discount_factor
action_bounds: $ action_bounds
action_init: $ action_init
predictor: $ predictor
critic: $ critic
