repos:
  - repo: local
    hooks:
      - id: black
        name: Auto-formatting (black)
        entry: black --version & exit 1
        language: python
        types: [ python ]
        additional_dependencies: [ 'black' ]
      # - id: ruff
      #   name: Linter (Ruff)
      #   entry: bash -c "ruff check ./regelum --ignore-noqa"
      #   language: system
      #   types: [ python ]
      #   require_serial: true
      # - id: pytest-check
      #   name: Full test 
      #   entry: pytest -n 2 -v
      #   language: system
      #   pass_filenames: false
      #   always_run: true

