site_name: Regelum
# site_url: https://james-willett.github.io/mkdocs-material-youtube-tutorial/
repo_name: Regelum
repo_url: https://github.com/AIDynamicAction/rcognita
docs_dir: ./docs/src
theme:
  name: material
  favicon: gfx/favicon_copy.svg
  logo: gfx/logo.svg
  features:
    - navigation.footer
    - content.code.annotate
    - navigation.tabs
    # - navigation.expand
    - toc.follow
    # - navigation.sections
    # - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    scheme: regelum
  

plugins:
  - termynal
  - search
  - autorefs
  - macros:
      include_dir: docs/include
  - gen-files:
      scripts:
      - docs/scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_options:
              ignore_init_summary: true
            members_order: source
            docstring_section_style: list
            filters: [""]
            heading_level: 1
            inherited_members: false
            merge_init_into_class: true
            separate_signature: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            # signature_crossrefs: true
            # show_symbol_type_toc: true
            # show_symbol_type_heading: true
            # docstring_section_style: list
            docstring_style: google
            # show_submodules: true
            # show_source: true
            # heading_level: 3
            # docstring_options:
            #   ignore_init_summary: true
            # merge_init_into_class: true
          paths: [regelum]
  - section-index
nav:
  - Home: index.md
  - Tutorials: tutorials/
  - Main features: features/
  - Getting started: getting_started.md
  - Scenarios: scenarios/
  - Reference API: reference/
  - Authors: authors.md
  - Systems: systems/

  # - Code Reference 2: references.md

extra_javascript:
  - _internal/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/npm/pseudocode@latest/build/pseudocode.min.js


extra_css:
  - _internal/stylesheets/colors.css

# extra:
#   social:
#     - icon: fontawesome/brands/github-alt
#       link: https://github.com/james-willett
#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/TheJamesWillett
#     - icon: fontawesome/brands/linkedin
#       link: https://www.linkedin.com/in/willettjames/

markdown_extensions:
  - tables
  - md_in_html
  - toc:
      toc_depth: 3
      permalink: ⚓︎
      title: On this page
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
# copyright: |
#   &copy; 2023 <a href="https://github.com/james-willett"  target="_blank" rel="noopener">James Willett</a>