_target_: rcognita.scenarios.OnlineScenario

###---Constructor arguments---###

running_objective: ~ running_objective
simulator: ~ simulator
is_log: false
howanim: None
state_init: $ initial_conditions.state_init
action_init: $ initial_conditions.action_init
N_episodes: 20
N_iterations: 1
speedup: 75
controller: ~ controller
observation_target: $ system_specific.observation_target
observation_components_naming: $ observation_naming.observation
