_target_: $ system_specific.target

#animations%%:
#  - BarAnimation
#  - PendulumAnimation

animations%%:
  - PendulumAnimation
  - ActionAnimation
  - StateAnimation
  - ObjectiveAnimation
  #- ScoreAnimation