#############################
###---A "defaults" list---###
#############################

defaults:
  - simulator: casadi
  - running_objective: running_objective
  - controller: calf

#################################
###---Constructor arguments---###
#################################

_target_: rcognita.scenarios.EpisodicScenarioMultirun

no_print: false
is_log: false
is_playback: false
state_init: = numpy.array([1, -1])
action_init: = numpy.array([0.5])
N_episodes: 8
N_iterations: 1
speedup: 75
observation_target: = []

#############################################################
###---A set of parameters forwarded into a global scope---###
#############################################################

######################
###---controller---###
######################

@controller.sampling_time: 1.0E-2

@controller.action_min%%: 0.
@controller.action_min%%: 1.
@controller.action_bounds: = numpy.array([[[${.action_min%%}], [${.action_max%%}]]])

#####################
###---Simulator---###
#####################

@simulator.time_start: 0.
@simulator.time_final: 70
@simulator.atol: 1.0E-5
@simulator.rtol: 1.0E-3

#############################
###---running objective---###
#############################

@running_objective.model.R1_diag%%: = [10., 10., 1.]

##############
###---AC---###
##############

@controller.actor.predictor.prediction_horizon: 0
@controller.safe_only: false
@controller.critic.safe_decay_param: 1.0E+4
@controller.critic.is_predictive: false

@controller.actor.safe_controller.actor.predictor.n_steps: 11
@controller.actor.safe_controller.actor.predictor.pred_step_size_multiplier%%: 220

# Nominal: 1235.11

