#############################
###---A "defaults" list---###
#############################

defaults:
  - simulator: casadi
  - running_objective: running_objective
  - controller: rpo
  - override controller/actor/optimizer: torch_projective
  - override controller/actor/model: weight_container_${controller/actor/optimizer}
  - override controller/actor/predictor: euler_multistep
  - override controller/critic/model: dqn
  - override controller/critic/optimizer: torch

#################################
###---Constructor arguments---###
#################################

_target_: rcognita.scenarios.EpisodicScenarioMultirun

no_print: false
is_log: false
is_playback: true
state_init: = numpy.array([-5., 5., 3. * numpy.pi / 4., 0., 0.])
action_init: = numpy.ones(2)
N_episodes: 30
N_iterations: 1
speedup: 75
observation_target: = []

#############################################################
###---A set of parameters forwarded into a global scope---###
#############################################################

######################
###---controller---###
######################

@controller.sampling_time: 1.0E-2

@controller.F_min%%: -300.
@controller.F_max%%: 300.
@controller.M_min%%: -100.
@controller.M_max%%: 100.

#####################
###---Simulator---###
#####################

@simulator.time_start: 0.
@simulator.time_final: 3
@simulator.atol: 1.0E-5
@simulator.rtol: 1.0E-3

#############################
###---running objective---###
#############################

@running_objective.model.R1_diag%%: = [10, 10, 1, 0, 0, 0, 0]

##############
###---AC---###
##############

@controller.actor.predictor.prediction_horizon: 0
@controller.actor.epsilon_greedy: true
@controller.actor.epsilon_greedy_parameter: 0.1

@controller.actor.optimizer.opt_options.lr: 0.5
@controller.actor.optimizer.iterations: 150

@controller.critic.data_buffer_size: 2
