_target_: rcognita.optimizers.TorchProjectiveOptimizer

bounds: $ controller.action_bounds

opt_options:
  lr: 0.1

iterations: 20
opt_method: = torch.optim.Adam
prediction_horizon: $ controller.actor.predictor.prediction_horizon