defaults:
  - model: fc 
  - optimizer: torch_dataloader

_target_: rcognita.actors.ActorDDPG

###---Constructor arguments---###
system: ~ system
<<<<<<< HEAD
dim_action: $ system.dim_action
dim_observation: $ system.dim_observation
=======
N_episodes: $ scenario.N_episodes
N_iterations: $ scenario.N_iterations
dim_output: $ system.dim_input
dim_input: $ system.dim_output
>>>>>>> 09088d3dfede6f8c14336bb3213b24e03b6b4f76
discount_factor: 1.
action_bounds: $ system.action_bounds%%
action_init: $ scenario.action_init
state_init: $ scenario.state_init
critic: ~ controller.critic
observation_target: $ system_specific.observation_target
running_objective: $ running_objective
device: cuda:0
is_use_derivative: $ system_specific.is_use_derivative
