defaults:
  - model: fc_gauss
  - optimizer: torch_dataloader


_target_: rcognita.actors.ActorPG


###---Constructor arguments---###
system: ~ system
N_episodes: $ scenario.N_episodes
N_iterations: $ scenario.N_iterations
dim_output: $ system.dim_input
dim_input: $ system.dim_output
discount_factor: 1.
action_bounds: $ system.action_bounds%%
action_init: $ scenario.action_init
state_init: $ scenario.state_init
critic: ~ controller.critic
observation_target: $ system_specific.observation_target
running_objective: $ running_objective
device: cuda:0
is_use_derivative: $ system_specific.is_use_derivative
