defaults:
  - model: fc_gauss
  - optimizer: torch_dataloader

_target_: rcognita.actors.ActorSDPG

###---Constructor arguments---###
system: ~ system
dim_output: $ system.dim_input
dim_input: $ system.dim_output
discount_factor: 1.
action_bounds: $ system.action_bounds%%
action_init: $ scenario.action_init
state_init: $ scenario.state_init
critic: ~ controller.critic
observation_target: $ system_specific.observation_target
running_objective: $ running_objective
device: cuda:0 
is_use_derivative: $ system_specific.is_use_derivative