defaults:
  - model: weight_container
  - optimizer: scipy
  - predictor: euler

_target_: rcognita.actors.ActorSQL

###---Constructor arguments---###
system: ~ system
prediction_horizon: $ controller.actor.predictor.prediction_horizon
dim_output: $ system.dim_input
dim_input: $ system.dim_output
discount_factor: 1.
action_bounds: $ system.action_bounds%%
action_init: $ scenario.action_init
state_init: $ scenario.state_init
critic: ~ controller.critic
observation_target: $ system_specific.observation_target