defaults:
  - simulator: default
  - running_objective: running_objective

_target_: rcognita.scenarios.EpisodicScenarioMultirun

###---Constructor arguments---###

no_print: false
is_log: false
is_playback: true
state_init: = numpy.array([numpy.pi, 0.0])
action_init: = numpy.ones(${simulator.system.dim_input})
N_episodes: 1
N_iterations: 1
speedup: 25
repeat_num: 1

### A set of parameters forwarded into a global scope


@simulator.ode_backend: SCIPY
@controller.sampling_time: 1.0E-2

@simulator.time_start: 0.
@simulator.time_final: 5.


### Actor and Critic


observation_target%%: = []

### Solver

@simulator.atol: 1.0E-5
@simulator.rtol: 1.0E-3



@running_objective.model.R1_diag%%: = [7., 0., 3.]

@controller.actor.safe_controller.controller_gain: 20
@controller.critic.safe_decay_param: 100
@controller.critic.critic_regularization_param: 0.

@controller.actor.predictor.prediction_horizon: 0


# default nominal total obj is 203.279