state_init%%: = numpy.array([2, -2]) 
action_init: = numpy.ones(${system.dim_input})

kwargs:
  _target_: builtins.dict
  size: 1

state_init: = ${.state_init%%} + numpy.random.normal(0., 0.5, ${.kwargs})