_target_: rcognita.controllers.Controller3WRobotPID

###---Constructor arguments---###

state_init: $ state_init
params: $ simulator.system.pars
time_start: $ simulator.time_start
sampling_time: 1.0E-2
action_bounds: = numpy.array([[${.F_min%%}, ${.F_max%%}], [${.M_min%%}, ${.M_max%%}]])


F_min%%: -300.
F_max%%: 300.
M_min%%: -100.
M_max%%: 100.