_target_: rcognita.predictors.RKPredictor

pred_step_size: $ sampling_time
system: $ system
dim_output: $ actor.dim_output
prediction_horizon: $ prediction_horizon
state_or_observation_init: $ state_init
action_init: $ action_init
