_target_: regelum.policy.RLPolicyPredictive

defaults:
  - model: weight_container_torch
  - predictor: euler 
  - optimizer_config: predictive_torch

system: ~ system
critic: ~ controller.critic
action_bounds: $ system_specific.action_bounds
discount_factor: $ scenario.discount_factor
running_objective: ~ running_objective
device: cpu
prediction_horizon: 1

model:
  dim_weights: = (${controller.policy.prediction_horizon}, ${system_specific.dim_action})