_target_: regelum.policy.PPO

defaults:
  - model: perceptron_with_normal_noise
  - optimizer_config: policy_gradient


system: ~ system
critic: ~ controller.critic
discount_factor: $ controller.discount_factor
device: cpu
epsilon: 0.2
running_objective_type: cost
sampling_time: $ system_specific.sampling_time

model:
  dim_hidden: 4
  n_hidden_layers: 2

