_target_: regelum.policy.DDPG

defaults:
  - model: perceptron_with_normal_noise
  - optimizer_config: policy_gradient

system: ~ system
critic: ~ controller.critic
discount_factor: $ scenario.discount_factor
device: cpu