_target_: regelum.policy.SDPG

defaults:
  - model: perceptron_with_normal_noise
  - optimizer_config: policy_gradient


system: ~ system
critic: ~ controller.critic
action_bounds: $ system_specific.action_bounds
discount_factor: $ scenario.discount_factor
device: cpu

