_target_: rcognita.policy.Reinforce

defaults:
  - model: perceptron_with_normal_noise

system: ~ system
action_bounds: $ system_specific.action_bounds
discount_factor: $ scenario.discount_factor
device: cpu

optimizer_config: 
  _target_: rcognita.OptimizerConfig
  callback_target_events: 
    - reset_iteration
  kind: tensor
  opt_method: = torch.optim.Adam
  opt_options: 
    lr: 0.1
  config_options:
    n_epochs: 1