_target_: rcognita.policy.Reinforce

defaults:
  - model: perceptron_with_normal_noise
  - optimizer_config: policy_gradient

system: ~ system
action_bounds: $ system_specific.action_bounds
discount_factor: $ scenario.discount_factor
device: cpu
