defaults:
  - actor: sdpg
  - critic: dqn_behaviour
  - episode_data_buffer: observation_action

name%%: sdpg

_target_: rcognita.controllers.RLController

###---Constructor arguments---###

time_start: $ simulator.time_start
sampling_time: $ system_specific.sampling_time
is_fixed_critic_weights: false
critic_period: = ${.critic_period_multiplier%%} * ${.sampling_time}
action_bounds: $ system.action_bounds%%

critic_period_multiplier%%: 1

critic:
  optimizer:
    opt_options:
      lr: 0.00001
  td_n: 10
  batch_size: 50
  discount_factor: 0.94


episode_data_buffer:
  is_use_derivative: $ system_specific.is_use_derivative
  is_cat_action: True
