defaults:
  - actor: sdpg
  - critic: critic_on_policy
  - data_buffer: data_buffer

name%%: sdpg

_target_: rcognita.controllers.PGController

###---Constructor arguments---###

time_start: $ simulator.time_start
sampling_time: $ system_specific.sampling_time
is_fixed_critic_weights: false
critic_period: = ${.critic_period_multiplier%%} * ${.sampling_time}
action_bounds: $ system.action_bounds%%

critic_period_multiplier%%: 1

critic:
  model:
    dim_hidden: 32
    is_double_precision: True
    bias: False
  optimizer:
    iterations: 50000 
    opt_options:
      lr: 0.001
  td_n: 10 
  batch_size: 100
  discount_factor: 1. 


  


