dim_input: ${dim_input}
dim_output: ${dim_output}
data_buffer_size: ${data_buffer_size}
optimizer: ${optimizer}
model: ${critic_model}
running_objective: ${running_objective}
discount_factor: ${discount_factor}
sampling_time: ${sampling_time}
critic_regularization_param: ${critic_regularization_param}
