_target_: rcognita.controllers.Controller3WRobotPID

###---Constructor arguments---###

state_init: $ initial_conditions.state_init
params: $ system.pars
time_start: $ simulator.time_start
sampling_time: 1.0E-2
action_bounds: $ system.action_bounds%%