defaults:
  - model: lookup_table


_target_: rcognita.critics.CriticTabularVI

dim_state_space: $ actor.dim_world
running_objective: ~ actor.running_objective
predictor: ~ actor.predictor
actor_model: ~ actor.model
discount_factor: $ actor.discount_factor
terminal_state: $ actor.terminal_state