defaults:
  - model: ddpg_actor 
  - optimizer: torch_dataloader


_target_: regelum.actors.ActorDDPG


###---Constructor arguments---###
system: ~ system
dim_action: $ system.dim_action
dim_observation: $ system.dim_observation
discount_factor: 1.
action_bounds: $ system.action_bounds%%
action_init: $ scenario.action_init
state_init: $ scenario.state_init
critic: ~ controller.critic
observation_target: $ system_specific.observation_target
running_objective: $ running_objective
device: cuda:0
batch_keys: = ["observation", "action", "observation_target", "timestamp"]