defaults:
  - model: weight_container
  - optimizer: scipy
  - predictor: euler

_target_: regelum.actors.ActorPID

###---Constructor arguments---###
system: ~ system
prediction_horizon: $ controller.actor.predictor.prediction_horizon
dim_action: $ system.dim_action%%
dim_observation: $ system.dim_observation%%
discount_factor: 1.
action_bounds: $ system.action_bounds%%
action_init: $ scenario.action_init
state_init: $ scenario.state_init
critic: ~ controller.critic
running_objective: $ running_objective

gain: 0.5