defaults:
  - model: fc_gauss
  - optimizer: torch_dataloader


_target_: regelum.actors.ActorREINFORCE


###---Constructor arguments---###
system: ~ system
N_episodes: $ scenario.N_episodes
N_iterations: $ scenario.N_iterations
dim_action: $ system.dim_action%%
dim_observation: $ system.dim_observation%%
discount_factor: 1.
action_bounds: $ system.action_bounds%%
action_init: $ scenario.action_init
state_init: $ scenario.state_init
critic: ~ controller.critic
observation_target: $ system_specific.observation_target
running_objective: $ running_objective
device: cuda:0
is_with_baseline: True 
is_do_not_let_the_past_distract_you: False
batch_keys: = ["observation", "action", "total_objective", "tail_total_objective", "baseline"]