defaults:
  - model: fc_gauss
  - optimizer: torch_dataloader


_target_: rcognita.actors.ActorSDPG


###---Constructor arguments---###
system: ~ system
dim_action: $ system.dim_action%%
dim_observation: $ system.dim_observation%%
N_episodes: $ scenario.N_episodes
N_iterations: $ scenario.N_iterations
dim_output: $ system.dim_input
dim_input: $ system.dim_output
discount_factor: 1.
action_bounds: $ system.action_bounds%%
action_init: $ scenario.action_init
state_init: $ scenario.state_init
critic: ~ controller.critic
observation_target: $ system_specific.observation_target
running_objective: $ running_objective
device: cuda:0
is_with_baseline: False 
is_do_not_let_the_past_distract_you: False
batch_keys: = ["observation", "action", "observation_target", "total_objective", "timestamp", "tail_total_objective", "baseline"]