defaults:
  - actor: mpc
  - critic: trivial

_target_: rcognita.controllers.RLController

###---Constructor arguments---###

time_start: $ simulator.time_start
sampling_time: 1.0E-2
is_fixed_critic_weights: false

F_l_min%%: -100.
F_l_max%%: 100.
F_t_min%%: -100.
F_t_max%%: 100.

critic_period: = ${.critic_period_multiplier%%} * ${.sampling_time}
action_bounds: = numpy.array([[${.F_l_min%%}, ${.F_l_max%%}], [${.F_t_min%%}, ${.F_t_max%%}]])

critic_period_multiplier%%: 1

