_target_: rcognita.models.GaussianPDFModel

dim_observation: = ${system_specific.dim_observation}
dim_action: = ${system_specific.dim_action}
dim_hidden: 4
std: 0.1
action_bounds: $ system_specific.action_bounds 
normalize_output_coef: 800.