_target_: regelum.OptimizerConfig

kind: tensor
opt_method: = torch.optim.SGD
opt_options: 
  lr: 3.0E-9
  momentum: 0.9
config_options:
  n_epochs: 1 
  constrained_optimization_policy:
    is_activated: True
    defaults:
      n_epochs_per_constraint: 200