defaults:
  - actor: calf
  - critic: calf
  - override actor/optimizer: casadi
  - override critic/optimizer: casadi

_target_: rcognita.controllers.CALFControllerExPost

###---Constructor arguments---###

time_start: $ simulator.time_start
sampling_time: 1.0E-2
is_fixed_critic_weights: false

M_min%%: -40.
M_max%%: 40.


critic_period: = ${.critic_period_multiplier%%} * ${.sampling_time}
action_bounds: = numpy.array([[${.M_min%%}, ${.M_max%%}]])

critic_period_multiplier%%: 1

###---Overrides---###

critic:
  is_predictive: false



