defaults:
  - model: gaussian_conditional

_target_: rcognita.actors.ActorProbabilisticEpisodic

###---Constructor arguments---###

dim_output: $ simulator.system.dim_input
dim_input: $ simulator.system.dim_output
action_bounds: $ controller.action_bounds
action_init: $ action_init
prediction_horizon: 0
