_target_: regelum.scenario.CALFTorch

name%%: calf

defaults:
  - critic_model: perceptron

running_objective: ~ running_objective
simulator: ~ simulator
prediction_horizon: 4
sampling_time: $ system_specific.sampling_time
observer: $ system_specific.observer
discount_factor: 1.0
safe_policy: ~ nominal_policy
policy_n_epochs: 10
critic_n_epochs: 10
critic_n_epochs_per_constraint: 20
critic_td_n: 10
critic_batch_size: 10
policy_opt_method_kwargs: 
  lr: 0.1
critic_opt_method_kwargs:
  lr: 0.1


critic_model:
  dim_input: = ${system_specific.dim_observation}
