_target_: rcognita.scenario.OnlineScenario

###---Constructor arguments---###

running_objective: ~ running_objective
simulator: ~ simulator
howanim: None 
N_episodes: 4 
N_iterations: 100
controller: ~ controller
observation_components_naming: $ observation_naming.observation
discount_factor: 1.0