_target_: regelum.scenario.REINFORCE

name%%: reinforce

defaults:
  - policy_model : perceptron_with_truncated_normal_noise

sampling_time: $ system_specific.sampling_time
running_objective: ~ running_objective
simulator: ~ simulator
observer: $ system_specific.observer
discount_factor: 1.0 

policy_n_epochs: 1
policy_opt_method: = torch.optim.Adam
policy_opt_method_kwargs: 
  lr: 0.1

N_iterations: 200
N_episodes: 3