_target_: regelum.scenario.SARSA

name%%: sarsa

defaults:
  - critic_model: perceptron

running_objective: ~ running_objective
simulator: ~ simulator
critic_td_n: 50
critic_batch_size: 100 
policy_n_epochs: 20
critic_n_epochs: 10
policy_opt_method_kwargs: 
  lr: 0.1
critic_opt_method_kwargs:
  lr: 0.0001
sampling_time: $ system_specific.sampling_time
observer: $ system_specific.observer
constraint_parser: ~ constraint_parser
discount_factor: 1.0
N_iterations: 20
epsilon_random_parameter: 0.05
stopping_criterion: ~ stopping_criterion


critic_model:
  dim_input: = ${system_specific.dim_observation} + ${system_specific.dim_action} 