_target_: rcognita.systems.LunarLander

###---Constructor arguments---###

dim_input: 2
dim_output: 6
sys_type: diff_eqn
dim_state: 6
dim_disturb: 6
pars: = [${.m%%}, ${.J%%}, ${.g%%}]

m%%: 10
J%%: 3.
g%%: 1.625
