defaults:
  - model: quad_no_mix
  - optimizer: casadi 

_target_: rcognita.critics.CriticOfObservation

###---Constructor arguments---###

system_dim_input: $ system.dim_input
system_dim_output: $ system.dim_output
data_buffer_size: 8
running_objective: ~ running_objective
discount_factor: $ controller.actor.discount_factor
sampling_time: $ controller.sampling_time
critic_regularization_param: 0

dim_critic_model_input%%: = ${.system_dim_output}
observation_target: $ system_specific.observation_target