rehydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}_${pipeline.name__IGNORE__}_${system_specific.name}
    subdir: ${rehydra.job.num}
  launcher:
    _target_: rehydra_plugins.rehydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: -1
    backend: null
    prefer: processes
    require: null
    verbose: 0
    timeout: null
    pre_dispatch: 2*n_jobs
    batch_size: auto
    temp_folder: null
    max_nbytes: null
    mmap_mode: r
  sweeper:
    _target_: rehydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${rehydra.job.name}
    header: '${rehydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://rehydra.cc)

      Use --rehydra-help to view Hydra specific help

      '
    template: '${rehydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${rehydra.help.footer}

      '
  rehydra_help:
    template: 'Hydra (${rehydra.runtime.version})

      See https://rehydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append rehydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg rehydra'' to Show the Hydra config.

      '
    rehydra_help: ???
  rehydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${rehydra.runtime.output_dir}/${rehydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .rehydra
  overrides:
    rehydra:
    - rehydra.job.chdir=True
    - rehydra/launcher=joblib
    - rehydra.mode=MULTIRUN
    task:
    - system=inv_pendulum
    - pipeline=pg
    - +seed=1
    - scenario=monte_carlo
    - scenario.N_iterations=20
    - system_specific.time_final=10
    - pipeline.actor.model.weight_max=20.0
    - pipeline.actor.model.weight_min=-20.0
    - pipeline.actor.optimizer.opt_options.lr=5.0
    - system_specific.diag_scale_coef=3.5
    - scenario.N_episodes=10
    - system_specific.total_objective_threshold=5000
  job:
    name: __init__
    chdir: true
    override_dirname: +seed=1,pipeline.actor.model.weight_max=20.0,pipeline.actor.model.weight_min=-20.0,pipeline.actor.optimizer.opt_options.lr=5.0,pipeline=pg,scenario.N_episodes=10,scenario.N_iterations=20,scenario=monte_carlo,system=inv_pendulum,system_specific.diag_scale_coef=3.5,system_specific.time_final=10,system_specific.total_objective_threshold=5000
    id: __init___0
    num: 0
    config_name: main
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /mnt/abolychev/regelum-research-calf/regelum-safe-pipelines/presets
    config_sources:
    - path: rehydra.conf
      schema: pkg
      provider: rehydra
    - path: /mnt/abolychev/regelum-research-calf/regelum-safe-pipelines/presets/general
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: /mnt/abolychev/regelum-research-calf/regelum-safe-pipelines/presets/multirun/2023-05-18/19-01-00_pg_inv_pendulum/0
    choices:
      pipeline: pg
      pipeline/episode_data_buffer: observation_action
      pipeline/critic: trivial
      pipeline/actor: pg
      pipeline/actor/optimizer: torch_dataloader
      pipeline/actor/optimizer/batch_sampler: none
      pipeline/actor/model: fc_gauss
      simulator: casadi
      scenario: monte_carlo
      system: inv_pendulum
      animator: animator_inv_pendulum
      system_specific: spec_inv_pendulum
      observation_naming: naming_inv_pendulum
      initial_conditions: ic_inv_pendulum_stochastic
      running_objective: quadratic_inv_pendulum
      running_objective/model: quad_form
      nominal_pipeline: nominal_inv_pendulum
      rehydra/env: default
      rehydra/callbacks: null
      rehydra/job_logging: default
      rehydra/rehydra_logging: default
      rehydra/rehydra_help: default
      rehydra/help: default
      rehydra/sweeper: basic
      rehydra/launcher: joblib
      rehydra/output: default
  verbose: false
