---
defaults:
  - controller:
      - rl_controller
      - default_controller
  - simulator: default_simulator
ode_solver: numpy
is_playback: true
no_visual: false
speedup: 5
no_print: false
sampling_time: 0.01
time_start: 0
time_final: 10
save_animation: true
penalty_param: 0
is_fixed_critic_weights: true
critic_period: 0.1
pi: "${get: numpy.pi}"
e: "${get: numpy.e}"
euler_gamma: "${get: numpy.euler_gamma}"
inf: "${get: numpy.inf}"
