defaults:
    - controller: ~ rl_controller
    - critic: ~ trivial
    - actor: ~ mpc
    - simulator: ~ simulator
    - objective: ~ running_objective

ode_solver: numpy
is_playback: true
no_print: false
no_visual: false
save_animation: true
speedup: 5

sampling_time: 1.0E-2
time_start: 0.
time_final: 10.

### Actor and Critic

penalty_param: 0.
is_fixed_critic_weights: true
critic_period_multiplier: 1.
critic_period: ${get:${critic_period_multiplier} * ${sampling_time}}
data_buffer_size: 10
discount_factor: 1.

### Controller

prediction_horizon: 3
pred_step_size_multiplier: 1.
