defaults:
  - model: weight_container
  - optimizer: scipy
  - predictor: euler

_target_: rcognita.actors.ActorMPC

running_objective: $ running_objective

###---Constructor arguments---###

prediction_horizon: $ controller.actor.predictor.prediction_horizon
dim_output: $ simulator.system.dim_input
dim_input: $ simulator.system.dim_output
discount_factor: 1.
action_bounds: $ controller.action_bounds%%
action_init: $ action_init
critic: ~ controller.critic
