_target_: rcognita.systems.System2Tank

dim_input: 1
dim_output: 2
sys_type: diff_eqn
dim_state: 2
dim_disturb: 2
pars: = [${.tau1%%}, ${.tau2%%}, ${.K1%%}, ${.K2%%}, ${.K3%%}]

K1%%: 1.3
K2%%: 1
K3%%: 0.2
tau1%%: 18.4
tau2%%: 24.4
