_target_: rcognita.models.GaussianElementWisePDFModel

dim_observation: $ controller.actor.dim_input
use_derivative: $ controller.actor.use_derivative
diag_scale_coef: $ system_specific.diag_scale_coef 
weight_max: 1
weight_min: = None

