_target_: regelum.critic.CriticCALF

defaults:
  - model: perceptron

discount_factor: $ scenario.discount_factor
sampling_time: $ controller.sampling_time
td_n: 1
device: cpu
is_same_critic: False
system: ~ system
safe_decay_param: 0.001
is_dynamic_decay_rate: False
lb_parameter: 1.0E-6
ub_parameter: 1.0E+3


model:
  dim_input: $ system_specific.dim_observation 

optimizer_config: 
  _target_: regelum.OptimizerConfig
  kind: tensor
  opt_method: = torch.optim.Adam
  opt_options: 
    lr: 3.0E-4
  config_options:
    n_epochs: 1 
    constrained_optimization_policy:
      is_activated: True
      defaults:
        n_epochs_per_constraint: 10
