_target_: regelum.critic.CriticCALF

defaults:
  - model: perceptron
  - optimizer_config: online_torch_sgd

discount_factor: $ controller.discount_factor
sampling_time: $ controller.sampling_time
td_n: 1
device: cpu
is_same_critic: False
system: ~ system
safe_decay_param: 0.001
is_dynamic_decay_rate: False
lb_parameter: 1.0E-5
ub_parameter: 1.0E+3


model:
  dim_input: $ system_specific.dim_observation 


