_target_: regelum.critic.CriticCALF

defaults:
  - model: quad_no_mix
  - optimizer_config: symbolic
  # - safe_controller: ~ nominal_controller

discount_factor: $ controller.discount_factor
sampling_time: $ controller.sampling_time
td_n: 1
device: cpu
is_same_critic: False
system: ~ system
safe_decay_param: 0.001
is_dynamic_decay_rate: False
lb_parameter: 1.0E-6
ub_parameter: 1.0E+3
regularization_param: 10


model:
  dim_inputs: $ system_specific.dim_observation 

optimizer_config:
  config_options:
    data_buffer_sampling_kwargs:
      n_samples: 2 