_target_: rcognita.models.ModelFc

dim_action: $ controller.actor.dim_output
dim_observation: $ controller.actor.dim_input
use_derivative: $ controller.actor.is_use_derivative
weight_min: = None
weight_max: 1