_target_: regelum.model.ModelWithOutputBounds

dim_input: $ system_specific.dim_observation
dim_output: $ system_specific.dim_action
dim_hidden: 4
n_hidden_layers: 1
leaky_relu_coef: 0.2
output_bounds: $ system_specific.action_bounds 
normalize_output_coef: 100.