defaults:
  - model: dqn_simple
  - optimizer: torch

_target_: rcognita.critics.CriticOfActionObservationOnPolicy

###---Constructor arguments---###

system_dim_input: $ system.dim_input
system_dim_output: $ system.dim_output
data_buffer_size: 8
running_objective: ~ running_objective
discount_factor: $ controller.actor.discount_factor
sampling_time: $ controller.sampling_time
dim_critic_model_input%%: = ${.system_dim_input} + ${.system_dim_output}
observation_target: $ system_specific.observation_target
state_init: $ scenario.state_init

