defaults:
  - model: dqn_simple
  - optimizer: torch

_target_: rcognita.critics.CriticOffPolicyBehaviour

system_dim_input: $ system.dim_input
system_dim_output: $ system.dim_output
data_buffer_size: $ system_specific.data_buffer_size
running_objective: $ running_objective
discount_factor: $ controller.actor.discount_factor
sampling_time: $ controller.sampling_time
state_init: $ scenario.state_init
critic_regularization_param: 0
batch_size: 30
td_n: 30
dim_critic_model_input%%: = ${.system_dim_input} + ${.system_dim_output}
