defaults:
  - actor: ddpg
  - critic: critic 
  - data_buffer: data_buffer

name%%: ddpg

_target_: regelum.controller.PGController

###---Constructor arguments---###

time_start: $ simulator.time_start
sampling_time: $ system_specific.sampling_time
is_fixed_critic_weights: false
critic_period: = ${.critic_period_multiplier%%} * ${.sampling_time}
action_bounds: $ system.action_bounds%%

critic_period_multiplier%%: 1
discount_factor%%: 1.0 

critic:
  is_same_critic: False
  model:
    dim_hidden: 16
    is_double_precision: True
    bias: True
    is_force_infinitesimal: True
  optimizer:
    iterations: 100 
    opt_options:
      lr: 0.01
  td_n: 128 
  batch_size: 100
  discount_factor: $ controller.discount_factor%%

actor:
  discount_factor: $ controller.discount_factor%%