defaults:
  - actor: mpc
  - critic: trivial

name%%: mpc

_target_: rcognita.controller.RLController

###---Constructor arguments---###

time_start: $ simulator.time_start
sampling_time: $ system_specific.sampling_time
is_fixed_critic_weights: false
action_bounds: $ system.action_bounds%%
critic_period: = ${.critic_period_multiplier%%} * ${.sampling_time}
critic_period_multiplier%%: 1

