defaults:
  - actor: rql
  - critic: dqn_behaviour 

name%%: rql

_target_: regelum.controller.RLController

###---Constructor arguments---###

time_start: $ simulator.time_start
sampling_time: $ system_specific.sampling_time
is_fixed_critic_weights: false
critic_period: = ${.critic_period_multiplier%%} * ${.sampling_time}
action_bounds: $ system.action_bounds%%
critic_period_multiplier%%: 1