defaults:
  - predictor: trivial
  - running_objective: running_objective
  - optimizer: bruteforce
  - model: lookup_table


_target_: rcognita.actors.ActorTabular

dim_world: = [9, 9]
action_space: = [0, 1, 2, 3, 4]
critic: ~ critic
discount_factor: 1.
terminal_state: = [4, 6]