_target_: rcognita.controllers.Controller3WRobotNIMotionPrimitive

###---Constructor arguments---###

time_start: $ simulator.time_start
sampling_time: $ controller.sampling_time
action_bounds: $ controller.action_bounds%%
K: 3