_target_: regelum.policy.RLPolicy

defaults:
  - model: weight_container
  - predictor: euler 
  - optimizer_config: symbolic

constraint_parser: ~ constraint_parser
system: ~ system
critic: ~ pipeline.critic
action_bounds: $ system_specific.action_bounds
discount_factor: $ pipeline.discount_factor
running_objective: ~ running_objective
device: cpu
prediction_horizon: 1
# algorithm: mpc

model:
  dim_output: $ system_specific.dim_action
  weights_init: = numpy.zeros((${pipeline.policy.prediction_horizon} + 1, ${.dim_output}))


