defaults:
  - actor: mpc
  - critic: trivial

_target_: rcognita.controllers.RLController

###---Constructor arguments---###

time_start: $ simulator.time_start
sampling_time: 1.0E-2
is_fixed_critic_weights: false

action_min%%: 0.
action_max%%: 1

critic_period: = ${.critic_period_multiplier%%} * ${.sampling_time}
action_bounds: = numpy.array([[[${.action_min%%}], [${.action_max%%}]]])

critic_period_multiplier%%: 1

