defaults:
  - default
  - actor: sql
  - critic: action_observation

_target_: rcognita.controllers.RLController

###---Constructor arguments---###

critic_period: = ${.critic_period_multiplier%%} * ${.sampling_time}

critic_period_multiplier%%: 1
action_bounds%%: = numpy.array([[${.F_min%%}, ${.F_max%%}], [${.M_min%%}, ${.M_max%%}]])