defaults:
  - simulator: default
  - running_objective: running_objective
  - override actor/model: weight_container
  - override critic/model: deep_objective
  - override actor/optimizer: torch_projective
  - override critic/optimizer: torch

_target_: rcognita.scenarios.EpisodicScenario

###---Constructor arguments---###

no_print: false
is_log: false
is_playback: true
state_init: = numpy.array([5., 5., 3. * numpy.pi / 4.])
action_init: = numpy.ones(2)
N_episodes: 1
N_iterations: 1
speedup: 25


### A set of parameters forwarded into a global scope


@simulator.ode_backend: SCIPY
@controller.sampling_time: 1.0E-2

@simulator.time_start: 0.
@simulator.time_final: 10.



@running_objective.model.R1_diag%%: = [1, 10, 1, 0, 0]
@running_objective.model.R2_diag%%: = [1, 10, 1, 0, 0]

### Actor and Critic

@controller.critic.model.dim_hidden: 5

observation_target%%: = []

### Solver

@simulator.atol: 1.0E-5
@simulator.rtol: 1.0E-3


@controller.actor.predictor.prediction_horizon: 1