_target_: rcognita.predictors.EulerPredictor

###---Constructor arguments---###

pred_step_size: = ${controller.sampling_time} * ${.pred_step_size_multiplier%%}
system: $ simulator.system
dim_observation: $ controller.actor.dim_observation
prediction_horizon: $ system_specific.mpc_prediction_horizon

pred_step_size_multiplier%%: 2
