_target_: rcognita.critics.CriticOfActionObservation

###---Constructor arguments---###

dim_input: $ actor.dim_input
dim_output: $ system.dim_output
data_buffer_size: $ data_buffer_size
optimizer: $ casadi
