defaults:
  - model: quad_no_mix
  - optimizer: scipy

defaults:
  - default

_target_: rcognita.critics.CriticOfActionObservation

###---Constructor arguments---###

dim_critic_model_input%%: = ${.system_dim_input} + ${.system_dim_output}

