defaults:
  - simulator: default
  - running_objective: running_objective

_target_: rcognita.scenarios.EpisodicScenarioMultirun

###---Constructor arguments---###

no_print: false
is_log: false
is_playback: true
state_init: = numpy.array([0, 5., 0., 0., 0., 0.])
action_init: = numpy.ones(2)
N_episodes: 1
N_iterations: 1
speedup: 75
repeat_num: 0

### A set of parameters forwarded into a global scope


@simulator.ode_backend: SCIPY
@controller.sampling_time: 1.0E-2

@simulator.time_start: 0.
@simulator.time_final: 10.

@controller.F_l_min%%: -300.
@controller.F_l_max%%: 300.
@controller.F_t_min%%: -300.
@controller.F_t_max%%: 300.


@running_objective.model.R1_diag%%: = [3, 3, 3, 5, 5, 5, 0, 0]
@running_objective.model.R2_diag%%: = [3, 3, 3, 5, 5, 5, 0, 0]



observation_target%%: = []

### Solver

@simulator.atol: 1.0E-5
@simulator.rtol: 1.0E-3

@controller.actor.predictor.prediction_horizon: 5
@controller.actor.epsilon_greedy: true
@controller.actor.epsilon_greedy_parameter: 0.5