_target_: regelum.controller.CALFControllerExPost

name%%: calf_ex_post_torch

defaults:
  - policy: policy_rpo_torch
  - critic: critic_calf_torch

action_bounds: $ system_specific.action_bounds
sampling_time: $ system_specific.sampling_time
running_objective: ~ running_objective
discount_factor: $ scenario.discount_factor
policy_optimization_event: compute_action
data_buffer_nullify_event: reset_episode
critic_optimization_event: compute_action
safe_controller: ~ nominal_controller

policy:
  prediction_horizon: 2

critic:
  is_on_policy: True
  is_value_function: True
  optimizer_config:
    config_options:
      n_epochs: 5
      is_reinstantiate_optimizer: False
      data_buffer_sampling_method: iter_batches
      data_buffer_sampling_kwargs:
        batch_sampler: = regelum.data_buffers.batch_sampler.RollingBatchSampler
        dtype: = torch.FloatTensor
        batch_size: 10
        n_batches: 1
        mode: backward

