_target_: regelum.controller.RLController

name%%: mpc

defaults:
  - policy: policy_mpc
  - critic: critic_trivial

action_bounds: $ system_specific.action_bounds
sampling_time: $ system_specific.sampling_time
is_critic_first: True 
running_objective: ~ running_objective
discount_factor: 1.0 
policy_optimization_event: = regelum.Event.compute_action
data_buffer_nullify_event: = regelum.Event.reset_episode

simulator: ~ simulator
N_episodes: 4 
N_iterations: 100
constraint_parser: ~ constraint_parser
observer: $ system_specific.observer

policy:
  prediction_horizon: 2
