_target_: regelum.controller.NominalControllerInvertedPendulum

name%%: nominal_inv_pendulum

###---Constructor arguments---###

time_start: 0
sampling_time: 1.0E-2
action_bounds: $ system_specific.action_bounds
controller_gain: 20
