_target_: regelum.controller.RLController

name%%: reinforce

defaults:
  - policy: policy_reinforce
  - critic: critic_trivial

action_bounds: $ system_specific.action_bounds
sampling_time: $ system_specific.sampling_time
is_critic_first: True
running_objective: ~ running_objective
discount_factor: $ scenario.discount_factor
policy_optimization_event: = regelum.Event.reset_iteration
data_buffer_nullify_event: = regelum.Event.reset_iteration
critic_optimization_event: = None

device%%: cpu
policy:
  model:
    dim_hidden: 4
    n_hidden_layers: 2
    normalize_output_coef: 100.
  optimizer_config: 
    opt_options:
      lr: 0.1
    config_options:
      is_reinstantiate_optimizer: False
      n_epochs: 1
  device: $ controller.device%%
