_target_: rcognita.controller.PGController

name%%: reinforce

defaults:
  - policy: policy_reinforce
  - critic: critic_trivial

action_bounds: $ system_specific.action_bounds
data_buffer: = rcognita.data_buffers.DataBuffer()
sampling_time: $ system_specific.sampling_time

device%%: cpu

policy:
  device: $ controller.device%%