_target_: regelum.controller.RLController

name%%: sql

defaults:
  - policy: policy_sql
  - critic: critic_polynom

action_bounds: $ system_specific.action_bounds
sampling_time: $ system_specific.sampling_time
is_critic_first: True
running_objective: ~ running_objective
discount_factor: $ scenario.discount_factor
policy_optimization_event: = regelum.Event.compute_action
data_buffer_nullify_event: = regelum.Event.reset_episode
critic_optimization_event: = regelum.Event.compute_action

policy:
  prediction_horizon: 1

critic:
  is_on_policy: True
  model:
    dim_inputs: = ${system_specific.dim_observation} + ${system_specific.dim_action}
  is_value_function: False