_target_: rcognita.controller.RLController

name%%: sql

defaults:
  - policy: policy_sql
  - critic: critic_polynom

action_bounds: $ system_specific.action_bounds
sampling_time: $ system_specific.sampling_time
is_critic_first: False
running_objective: ~ running_objective
discount_factor: $ scenario.discount_factor
policy_optimization_event: compute_action
data_buffer_nullify_event: reset_episode
critic_optimization_event: = None

policy:
  predictor:
    prediction_horizon: 2

critic:
  model:
    dim_inputs: = ${system_specific.dim_observation} + ${system_specific.dim_action}
  is_value_function: False