_target_: rcognita.controllers.Controller3WRobotDisassembledCLF

m: $ simulator.system.m%%
I: $ simulator.system.I%%
action_bounds: $ controller.action_bounds%%
time_start: $ simulator.time_start
sampling_time: $ controller.sampling_time
max_iters: 200