_target_: regelum.scenario.MonteCarloScenario

###---Constructor arguments---###

running_objective: ~ running_objective
simulator: ~ simulator
howanim: None 
state_init: $ initial_conditions.state_init
action_init: $ initial_conditions.action_init
N_episodes: 20
N_iterations: 1
speedup: 75
controller: ~ controller
observation_target: $ system_specific.observation_target
observation_components_naming: $ observation_naming.observation
total_objective_threshold: $ system_specific.total_objective_threshold