_target_: regelum.OptimizerConfig
kind: symbolic
opt_method: ipopt
opt_options: 
  print_level: 0
log_options:
  print_in: False
  print_out: False
  print_time: False
config_options:
  data_buffer_sampling_method: sample_last
  data_buffer_sampling_kwargs:
    dtype: = casadi.DM