_target_: rcognita.system.ThreeWheeledRobot


animations%%:
  - DirectionalPlanarMotionAnimation
  - BarAnimation

###---Constructor arguments---###

system_parameters_init: 
  _target_: builtins.dict
  m: 10.
  I: 1.

###---Off-constructor variables---###

F_min%%: -300.
F_max%%: 300.
M_min%%: -100.
M_max%%: 100.
action_bounds%%: = numpy.array([[${.F_min%%}, ${.F_max%%}], [${.M_min%%}, ${.M_max%%}]])

dim_action%%: 2
dim_observation%%: 5 
