_target_: rcognita.systems.SysKinematicPoint

###---Constructor arguments---###

dim_input: ${.dim_kin_point_system%%}
dim_output: ${.dim_kin_point_system%%}
sys_type: diff_eqn
dim_state: ${.dim_kin_point_system%%}
dim_disturb: ${.dim_kin_point_system%%}

dim_kin_point_system%%: 2

pars: = []

bound%%: 50
action_bounds%%: = numpy.hstack([numpy.full((${.dim_kin_point_system%%}, 1), -${.bound%%}), numpy.full((${.dim_kin_point_system%%}, 1), ${.bound%%})])

