defaults:
  - model: ddqn
  - optimizer: torch

_target_: regelum.critic.CriticOffPolicyBehaviour

system_dim_input: $ system.dim_action%%
system_dim_output: $ system.dim_observation%%
data_buffer_size: $ system_specific.data_buffer_size
running_objective: $ running_objective
discount_factor: $ controller.actor.discount_factor
sampling_time: $ controller.sampling_time
critic_regularization_param: 0
state_init: $ scenario.state_init
batch_size: 30
td_n: 30
dim_critic_model_input%%: = ${.system_dim_input} + ${.system_dim_output}