defaults:
  - model: dqn
  - optimizer: torch

_target_: rcognita.critics.CriticOffPolicyBehaviour



system_dim_input: $ system.dim_input
system_dim_output: $ system.dim_output
data_buffer_size: 1000
running_objective: $ running_objective
discount_factor: $ controller.actor.discount_factor
sampling_time: $ controller.sampling_time
critic_regularization_param: 0
batch_size: 10
td_n: 5
dim_critic_model_input%%: = ${.system_dim_input} + ${.system_dim_output}