defaults:
  - model: quad_no_mix
  - optimizer: casadi 

_target_: rcognita.critic.CriticOfObservation

###---Constructor arguments---###

system_dim_input: $ system.dim_action%%
system_dim_output: $ system.dim_observation%%
data_buffer_size: 8
running_objective: ~ running_objective
discount_factor: $ controller.actor.discount_factor
sampling_time: $ controller.sampling_time
state_init: $ scenario.state_init
critic_regularization_param: 0

dim_critic_model_input%%: = ${.system_dim_output}
observation_target: $ system_specific.observation_target