_target_: regelum.model.ModelQuadLin

###---Constructor arguments---###

weights: = numpy.array(${.R1_diag%%})
quad_matrix_type: diagonal
is_with_linear_terms: False
R1_diag%%: = [10., 10., 1., 0., 0., 0., 0.]
