defaults:
  - simulator: default
  - running_objective: running_objective

_target_: rcognita.scenarios.EpisodicScenario

###---Constructor arguments---###

no_print: false
is_log: false
is_playback: true
state_init: = numpy.array([1, -1])
action_init: = numpy.array([0.5])
N_episodes: 1
N_iterations: 1
speedup: 25


### A set of parameters forwarded into a global scope


@simulator.ode_backend: SCIPY
@controller.sampling_time: 1.0E-1

@simulator.time_start: 0.
@simulator.time_final: 10.



@running_objective.model.R1_diag%%: = [10., 10., 1.]
@running_objective.model.R2_diag%%: = [10., 10., 1.]

### Actor and Critic



observation_target: = numpy.array([0.4, 0.4])

### Solver

@simulator.atol: 1.0E-5
@simulator.rtol: 1.0E-3


