_target_: rcognita.controllers.Controller3WRobotNIMotionPrimitive

###---Constructor arguments---###

K: 3
time_start: $ simulator.time_start
sampling_time: 1.0E-2
action_bounds: $ system.action_bounds%%