_target_: rcognita.models.ModelBiquadForm

###---Constructor arguments---###

weights: = [numpy.diag(${.R1_diag%%}), numpy.diag(${.R2_diag%%})]

R1_diag%%: = [-10., 0., -3., 1.]
R2_diag%%: = [-10., 0., -3., 1.]
