defaults:
  - system: three_wheel_robot

_target_: rcognita.simulator.Simulator

sys_type: $ simulator.system.sys_type
state_init: $ state_init
action_init: $ action_init
disturb_init: = None
time_start: $ time_start%%
time_final: $ time_final%%
sampling_time: $ sampling_time%%
max_step: $ max_step%%
first_step: 1.0E-6
atol: $ atol%%
rtol: $ rtol%%
ode_solver: $ ode_solver%%
