defaults:
  - simulator: default
  - running_objective: running_objective


_target_: rcognita.scenarios.EpisodicScenario

###---Constructor arguments---###

no_print: false
is_log: false
is_playback: true
state_init: = numpy.array([-5., 5., 3. * numpy.pi / 4., 10., 3.])
action_init: = numpy.ones(2)
N_episodes: 7
N_iterations: 1
speedup: 75


### A set of parameters forwarded into a global scope


@simulator.ode_backend: CASADI
@controller.sampling_time: 1.0E-2

@simulator.time_start: 0.
@simulator.time_final: 10.

@controller.F_min%%: -300.
@controller.F_max%%: 300.
@controller.M_min%%: -100.
@controller.M_max%%: 100.


@running_objective.model.R1_diag%%: = [10, 10, 1, 0, 0, 0, 0]
@running_objective.model.R2_diag%%: = [1, 10, 1, 0, 0, 0, 0]



observation_target%%: = []

### Solver

@simulator.atol: 1.0E-5
@simulator.rtol: 1.0E-3

@controller.actor.predictor.prediction_horizon: 0

@controller.critic.safe_decay_param: 1000