defaults:
  - actor: calf
  - critic: calf
  - override actor/optimizer: casadi
  - override critic/optimizer: casadi

_target_: rcognita.controllers.CALFControllerExPost

###---Constructor arguments---###

time_start: $ simulator.time_start
sampling_time: 1.0E-2
is_fixed_critic_weights: false
critic_period: = ${.critic_period_multiplier%%} * ${.sampling_time}
critic_period_multiplier%%: 1

###---Overrides---###

critic:
  is_predictive: true

actor:
  predictor:
    prediction_horizon: 0

action_min%%: 0.
action_max%%: 1.
action_bounds: = numpy.array([[[${.action_min%%}], [${.action_max%%}]]])




