#############################
###---A "defaults" list---###
#############################

defaults:
  - actor: rpo
  - critic: observation
  - override actor/optimizer: torch_projective
  - override actor/model: weight_container
  - override critic/model: dqn
  - override critic/optimizer: torch
  - action_bounds_${simulator.system}

#################################
###---Constructor arguments---###
#################################
_target_: rcognita.controllers.RLController

time_start: $ simulator.time_start
sampling_time: 1.0E-2
is_fixed_critic_weights: false

critic_period: = ${.critic_period_multiplier%%} * ${.sampling_time}

critic_period_multiplier%%: 1

