defaults:
  - actor: rql
  - critic: action_observation
  - action_bounds_${simulator.system}

_target_: rcognita.controllers.RLController

###---Constructor arguments---###

time_start: $ simulator.time_start
sampling_time: 1.0E-2
is_fixed_critic_weights: false

critic_period: = ${.critic_period_multiplier%%} * ${.sampling_time}
critic_period_multiplier%%: 1