_target_: rcognita.system.ThreeWheeledRobotNI

###---Constructor arguments---###

system_parameters_init: 
  _target_: builtins.dict
  
###---Off-constructor variables---###

v_min%%: -25.
v_max%%: 25.
omega_min%%: -5.
omega_max%%: 5.
action_bounds%%: = numpy.array([[${.v_min%%}, ${.v_max%%}], [${.omega_min%%}, ${.omega_max%%}]])

dim_action%%: 2
dim_observation%%: 3 