_target_: rcognita.system.CartPole

###---Constructor arguments---###

system_parameters_init: 
  _target_: builtins.dict
  m_c: 0.1
  m_p: 2.
  g: 9.81
  l: 0.5

###---Off-constructor variables---###

F_min%%: -300.
F_max%%: 300.
action_bounds%%: = numpy.array([[${.F_min%%}, ${.F_max%%}]])

dim_action%%: 1
dim_observation%%: 4 
