_target_: rcognita.systems.InvertedPendulumPD

###---Constructor arguments---###

system_parameters_init: 
  _target_: builtins.dict
  m: 1.
  g: 9.81
  l: 1.

###---Off-constructor variables---###

M_min%%: -200. 
M_max%%: 200.
action_bounds%%: = numpy.array([[${.M_min%%}, ${.M_max%%}]])

dim_action%%: 1
dim_observation%%: 2 