_target_: rcognita.systems.LunarLander

###---Constructor arguments---###

system_parameters_init: 
  _target_: builtins.dict
  m: 10.
  J: 3.
  g: 9.81

###---Off-constructor variables---###

F_l_min%%: -300.
F_l_max%%: 300.
F_t_min%%: -300.
F_t_max%%: 300.
action_bounds%%: = numpy.array([[${.F_l_min%%}, ${.F_l_max%%}], [${.F_t_min%%}, ${.F_t_max%%}]])

dim_action%%: 2
dim_observation%%: 6 