_target_: rcognita.optimizers.TorchDataloaderOptimizer

defaults:
  - batch_sampler: none

opt_options:
  lr: 1.0E-3

batch_size: 50
epochs: 50
opt_method: = torch.optim.Adam
model: ~ controller.actor.model
