_target_: rcognita.models.GaussianPDFModel

dim_observation: $ controller.actor.dim_input
dim_action: $ controller.actor.dim_output
use_derivative: $ controller.actor.use_derivative
diag_scale_coef: 1
