_target_: rcognita.models.GaussianPDFModel

dim_observation: $ controller.actor.dim_input
dim_action: $ controller.actor.dim_output
use_derivative: $ controller.actor.use_derivative
diag_scale_coef: $ system_specific.scale_diag_coef 
weight_max: 1
weight_min: = None

