_target_: regelum.model.ModelFc

dim_output: $ controller.actor.dim_action
dim_input: $ controller.actor.dim_observation
use_derivative: $ controller.actor.is_use_derivative
weight_min: = None
weight_max: 1