_target_: regelum.model.ModelPerceptron

# Redefine dim_input in critic config
dim_input: 0
dim_output: 1
dim_hidden: 20
n_hidden_layers: 2

is_force_infinitesimal: False
is_bias: False
force_positive_def: False
